---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install GitLab and its dependencies (RedHat).
- name: Install GitLab dependencies (RedHat).
  yum: "pkg={{ item }} state=installed"
  with_items:
    - openssh-server
    - postfix
  when: ansible_os_family == 'RedHat'

- name: Install GitLab rpm (RedHat).
  command: >
    rpm --nosignature -i {{ gitlab_package_url }}
    creates=/usr/bin/gitlab-ctl
  when: ansible_os_family == 'RedHat'

# Install GitLab and its dependencies (Debian).
- name: Install GitLab dependencies (Debian).
  apt: "pkg={{ item }} state=installed"
  with_items:
    - openssh-server
    - postfix
  when: ansible_os_family == 'Debian'

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Download GitLab .deb package (Debian).
  get_url: >
    url={{ gitlab_package_url }}
    dest=/tmp/gitlab.deb
  when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'Debian')

- name: Install GitLab .deb package (Debian).
  command: sudo dpkg -i /tmp/gitlab.deb
  when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'Debian')

# This will work in Ansible 1.6+.
# - name: Install GitLab .deb package (Debian).
#   apt: deb=/tmp/gitlab.deb

# Start and configure GitLab.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped

- name: Create GitLab SSL configuration folder.
  file: >
    path=/etc/gitlab/ssl
    state=directory
    owner=root group=root mode=700
  when: gitlab_create_self_signed_cert

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}" -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: gitlab_create_self_signed_cert

- name: Copy GitLab configuration file.
  template: >
    src=templates/gitlab.rb.j2
    dest=/etc/gitlab/gitlab.rb
    owner=root group=root mode=600
  notify: restart gitlab
